<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '';
echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="container">';
echo '<div class="row mt-5 justify-content-center">';
echo '<div class="col-md-6 ">';
echo '<h1>Fill Form</h1><hr>';
echo '<form action="createUserAndPost.php" method="post">';
echo '<div class="form-group">';
echo '<label for="">User Name</label>';
echo '<input required type="text" class="form-control" name="user_name">';
echo '</div>';
echo '<div class="form-group">';
echo '<label for="">User Email</label>';
echo '<input required type="email" class="form-control" name="user_email">';
echo '</div>';
echo '<div class="form-group">';
echo '<label for="">Post Title</label>';
echo '<input required type="text" class="form-control" name="post_title">';
echo '</div>';
echo '<div class="form-group">';
echo '<label for="">Post Body</label>';
echo '<input required type="text" class="form-control" name="post_body">';
echo '</div>';
echo '<button class="btn btn-primary btn-block" name="submit">Submit</button>';
echo '</form>';
echo '<br>';
echo '<a href="search.php">Search Posts</a><br>';
echo '<a href="curl_users.php">Add all users by clicking once</a><br>';
echo '<a href="curl_posts.php">Add all posts by clicking once</a><br>';
echo '<a href="averagePosts.php">Average</a><br>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>';
echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>';
echo '</body>';
echo '';
echo '</html>';
echo '';
?>